spring:
  config:
    import: optional:secrets.yaml
  devtools:
    livereload:
      enabled: true
      port: 32729
  application:
    name: bookHaven
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
